#!/bin/bash

export ARM_CLIENT_ID=${INPUT_ARM_CLIENT_ID}
export ARM_CLIENT_SCERET=${INPUT_ARM_CLIENT_SECRET}
export ARM_SUBSCRIPTION_ID=${INPUT_ARM_SUBSCRIPTION_ID}
export ARM_TENANT_ID=${INPUT_ARM_TENANT_ID}
export ARM_STATE_ID=${INPUT_STATE_KEY}
export TF_STAGE=${INPUT_TF_STAGE}

terraform plan
terraform apply --auto-approve

