name: 'Terraform container actions'
description: 'Terraform action'

inputs:
  ARM_CLIENT_ID:
    description: Azure client id
    required: true
  ARM_CLIENT_SECRET:
    description: Azure client secret
    required: true
  ARM_SUBSCRIPTION_ID:
    description: Azure subscription id
    required: true
  ARM_TENANT_ID:
    description: Azure tenant id
    required: true
  STATE_KEY:
    description: Terraform state key
    required: true
  TF_STAGE:
    description: Terraform stage folder
    required: true
  DJANGO_SECRET_KEY_PROD:
    description: 'The secret key for django to startup'
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: box
  color: blue
